# Generated by Django 5.0 on 2023-12-14 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0003_histroicalperfomancemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseordermodel',
            name='acknowledgment_date',
            field=models.DateTimeField(null=True),
        ),
    ]
