# Generated by Django 5.0 on 2023-12-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0004_alter_purchaseordermodel_acknowledgment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseordermodel',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('completed', 'completed'), ('canceled', 'canceled')], default='pending', max_length=10),
        ),
    ]
