# Generated by Django 5.0 on 2023-12-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0005_alter_purchaseordermodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendormodel',
            name='average_response_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='vendormodel',
            name='fulfillment_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='vendormodel',
            name='on_time_delivery_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='vendormodel',
            name='quality_rating_avg',
            field=models.FloatField(default=0.0),
        ),
    ]
