# Generated by Django 5.0 on 2023-12-15 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0007_alter_purchaseordermodel_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseordermodel',
            name='acknowledgment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseordermodel',
            name='quality_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
